### ISSUE TITLE
Request to add GEOSEARCH example application

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/adding-apps-to-redis-marketplace#12]
This is already in the redis-developer GitHub org:

https://github.com/redis-developer/introducing-the-geosearch-command

I've added a `marketplace.json` file for you.

**Comment by ajeetraina** [comment]
Hi @simonprickett Looks to be an interesting app.
I will be uploading it to LaunchPad by a short name "Rail Station Finder"

**Comment by simonprickett** [comment]
@ajeetraina thanks!

**Comment by ajeetraina** [comment]
Hello @simonprickett I have added your app to LaunchPad https://launchpad.redis.com/?id=project%3Aintroducing-the-geosearch-command

Is it possible to change the repository name to https://github.com/redis-developer/rail-station-finder? We usually keep the repo a short name. OR we can create a new repository with this new one? What do you think?

**Comment by simonprickett** [comment]
I'm going to leave the repo name as is, as it appears in videos we've made.
