### ISSUE TITLE
Add SkillMarket to the LaunchPad site

### ISSUE THREAD

**Issue by julianmateu** [redis-developer/adding-apps-to-redis-marketplace#16]
This is a request to add Skillmaster app. 

https://developer.redis.com/howtos/socialnetwork/

https://github.com/julianmateu/skillmarket-backend
https://github.com/julianmateu/skillmarket-front

**Comment by ajeetraina** [comment]
Closing this as it is already added to the LaunchPad https://launchpad.redis.com/?id=project%3Askillmarket
