### ISSUE TITLE
Fork request

### ISSUE THREAD

**Issue by fnatte** [redis-developer/adding-apps-to-redis-marketplace#2]
Hi,

I've registered and submitted a project for the Build on Redis Hackathon. I added a `marketplace.json`. Please let me know if there are any issues.

Feel free to fork it at https://github.com/fnatte/pizza-tribes.

Thanks,
Matteus

**Comment by ajeetraina** [comment]
HI @fnatte We have added your app to the LaunchPad https://launchpad.redis.com/?id=project%3Apizza-tribes
Thanks for your contribution.
