### ISSUE TITLE
Fork request

### ISSUE THREAD

**Issue by niekcandaele** [redis-developer/adding-apps-to-redis-marketplace#3]
Hi,

We've registered a project on Redis hackathon and added a marketplace.json file. Please let me know if there are any issues.

https://github.com/niekcandaele/feature-creep

Thanks,
Niek

**Comment by ajeetraina** [comment]
@niekcandaele We have added your app to LaunchPad https://launchpad.redis.com/?id=project%3Afeature-creep

**Comment by ajeetraina** [comment]
Closing this as it is already added to then LaunchPad.
