### ISSUE TITLE
Fork request: The Pattern: Machine Learning Natural Language Processing meets VR/AR

### ISSUE THREAD

**Issue by AlexMikhalev** [redis-developer/adding-apps-to-redis-marketplace#4]
Can you please fork project: 
https://github.com/applied-knowledge-systems/the-pattern

**Comment by ajeetraina** [comment]
@AlexMikhalev We have added your project under https://launchpad.redis.com/?id=project%3Athe-pattern

**Comment by ajeetraina** [comment]
Closing this as it is already added to then LaunchPad.
