### ISSUE TITLE
Fork Request

### ISSUE THREAD

**Issue by sarthakarora1208** [redis-developer/adding-apps-to-redis-marketplace#5]
Hi,

I have made a project for the Redis 2021 hackathon and added a marketplace.json file. Please do let me know if there are any issues.

Repository Link: [https://github.com/sarthakarora1208/Reeko-Slack-Bot](https://github.com/sarthakarora1208/Reeko-Slack-Bot)

Regards,
Sarthak Arora

**Comment by ajeetraina** [comment]
@sarthakarora1208 Added https://launchpad.redis.com/?id=project%3AReeko-Slack-Bot

**Comment by ajeetraina** [comment]
Closing this as it is already added to the LaunchPad.
