### ISSUE TITLE
Fork Request

### ISSUE THREAD

**Issue by serdeliverance** [redis-developer/adding-apps-to-redis-marketplace#7]
Hi,

I have made a project for the Redis 2021 hackathon and added a marketplace.json file. Please do let me know if there are any issues.

Repository Link: https://github.com/serdeliverance/x-mentor

Regards,
Sergio Cano

**Comment by ajeetraina** [comment]
Closing this as we have already added X-mentor to LaunchPad https://launchpad.redis.com/?id=project%3Ax-mentor
