### ISSUE TITLE
Fork Request: Redis 

### ISSUE THREAD

**Issue by anagnoad** [redis-developer/adding-apps-to-redis-marketplace#8]
Hi Redis team,

We have made a project for the Redis 2021 hackathon! :) As per the instructions, here is a fork request.
Repository Link: https://github.com/ABettaMe/abetta-ux
Organisation Link (containing all applicable micro-repos): https://github.com/ABettaMe

Thank you very much in advance,
Antonis Anagnostou

**Comment by ajeetraina** [comment]
I have added this app to Redis LaunchPad https://launchpad.redis.com/?id=project%3Aabetta-ux

Thanks for your valuable contribution. Closing this issue.
