### ISSUE TITLE
Fork request: for redis hackaton

### ISSUE THREAD

**Issue by byronrosas** [redis-developer/adding-apps-to-redis-marketplace#9]
Hi,

I've registered and submitted a project for the Build on Redis Hackathon. I added a marketplace.json. 

Feel free to fork it at my github
https://github.com/byronrosas/helplanet

Thanks,
Byron

**Comment by ajeetraina** [comment]
I have added this app to LaunchPad. https://launchpad.redis.com/?id=project%3Ahelplanet

Thanks for the contribution. Closing this issue.
